config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'stories#index'
  resources :stories do
    patch 'make_as_read', to: 'stories#make_as_read'
    patch 'make_as_unread', to: 'stories#make_as_unread'
  end
  get 'search', to: 'stories#search', as: :collection
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/story.rb
class Story < ApplicationRecord
  validates :title, :description, presence: true
  after_create_commit { broadcast_prepend_to 'stories' }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:make_as_read, :make_as_unread]
  before_action :set_story, only: [:show, :edit, :update, :destroy, :make_as_read, :make_as_unread]

  def index
    @stories = Story.all.order(created_at: :desc)
  end

  def new
    @story = Story.new
  end
  
  def show; end

  def create
    @story = Story.new(story_params)
    respond_to do |format|
      if @story.save
        format.html { redirect_to stories_path, notice: "Story was successfully destroyed." }
      else
        format.html { render :new }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to stories_path }
        format.turbo_stream { render turbo_stream: turbo_stream.replace("story_#{@story.id}", partial: 'story', locals: { story: @story }) }
      else
        format.html { redirect_to edit_story_path }
      end
    end
  end

  def destroy
    respond_to do |format|
      if @story.destroy
        format.html { redirect_to stories_path }
        format.turbo_stream
      else
        format.html { redirect_to stories_path, notice: @story.errors.full_message }
      end
    end
  end

  # GET /search?search='abc'
  def search
    @stories = Story.where("title LIKE ?", "%#{params[:search]}%").order(created_at: :desc)
    respond_to do |format|
      format.json { render json: render_to_string(partial: 'stories/story', collection: @stories, formats: [:html])}
    end
  end

  # PATCH stories/:story_id/make_as_read
  def make_as_read
    @story.update(mark_as_read: true)
    respond_to do |format|
      format.json { render json: render_to_string(partial: 'stories/story', locals: {story: @story}, formats: [:html])}
    end
  end
  
  # PATCH stories/:story_id/make_as_unread
  def make_as_unread
    @story.update(mark_as_read: false)
    respond_to do |format|
      format.json { render json: render_to_string(partial: 'stories/story', locals: {story: @story}, formats: [:html])}
    end
  end

  private
  def story_params
    params.require(:story).permit(:title, :description)
  end

  def set_story
    @story = if params[:id].present?
              Story.find(params[:id])
             elsif params[:story_id].present?
              Story.find(params[:story_id])
             end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryBook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <div class='m-4'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: @story, local: true) do |f| %>
  <% if @story.errors.any? %>
    <div class="alert alert-danger mt-2" role="alert">
      <ul>
        <% @story.errors.full_messages.each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group mt-3">
    <%= f.label :title %>
    <div class="col-md-8">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>

  <div class="form-groupmt-3 field">
    <%= f.label :description %>
    <div class="col-md-8">
      <%= f.text_area :description, class: "form-control" %>
    </div>
  </div>

  <div class="form-group mt-3">
    <%= f.submit class: 'btn btn-success' %>
    <%= link_to 'Back', stories_path, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/stories/_story.html.erb
<%= turbo_frame_tag "story_#{story.id}" do %>
  <div style='border-style: ridge; padding: 20px;', class='mt-2'>
    <b><%= story.title %></b><br>
    <%= story.description.truncate(200) %><br>
    <div class='mt-2 d-flex'>
      <%= link_to story_path(story) do %>
        <%= fa_icon "eye" %>
      <% end %>
      <%= link_to edit_story_path(story), style: 'margin-left: 5px' do %>
        <%= fa_icon "pencil" %>
      <% end %>
      <%= link_to story_path(story), style: 'margin-left: 5px', data: {confirm: "Are you sure?", "turbo-method": :delete} do %>
        <%= fa_icon "trash" %>
      <% end %>   

      <%# Mark as read & unread %>
      <div data-controller='make-as-read-unread'>
        <% if story.mark_as_read? %>
          <%= link_to '/', style: 'margin-left: 5px', remote: true,
              data: {
                controller: 'make-as-read-unread',
                action: 'click->make-as-read-unread#unread', 
                'make-as-read-unread-url-value': story_make_as_unread_path(story_id: story.id),
                'make-as-read-unread-story-id-value': story.id
              }, "data-toggle" => "tooltip", "data-placement" => "right", "title" => "Make As Unread" do %>
            <%= fa_icon "envelope-open" %>
          <% end %>
        <% else %>
          <%= link_to '/', style: 'margin-left: 5px', remote: true,
              data: {
                controller: 'make-as-read-unread',
                action: 'click->make-as-read-unread#read',
                'make-as-read-unread-url-value': story_make_as_read_path(story_id: story.id),
                'make-as-read-unread-story-id-value': story.id
              }, "data-toggle" => "tooltip", "data-placement" => "right", "title" => "Make As Read" do %>
            <%= fa_icon "envelope" %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/stories/destroy.turbo_stream.erb
<%= turbo_stream.remove "story_#{@story.id}" %>

app/views/stories/edit.html.erb
<h2>Edit Story</h2>
    
<%= turbo_frame_tag "story_#{@story.id}" do %>
  <%= render partial: 'form', object: @story %>
<% end %>

app/views/stories/index.html.erb
<%= turbo_frame_tag "create_story_form" do %>
  <%= link_to 'Create new story', new_story_path, class: 'btn btn-dark' %>
<% end %>

<div class='mt-4' data-controller='search'>
  <%= text_field_tag :query,'', placeholder: 'Search by title', data: {action: 'input->search#search', target: 'search.params'}%>
</div>

<h2 class='mt-3'>Stories</h2>

<%= turbo_stream_from 'stories' %>
<%= turbo_frame_tag "stories" do %>
  <% if @stories.any? %>
    <%= render @stories %>
  <% else %>
    <p>No stories available</p>
  <% end %>
<% end %>

app/views/stories/new.html.erb
<h2>New Story</h2>

<%= turbo_frame_tag "create_story_form" do %>
  <%= render partial: 'form', object: @story %>
<% end %>

app/views/stories/show.html.erb
<p style='border-style: ridge; padding: 20px;'>
  <b><%= @story.title %></b><br>
  <%= @story.description %><br>
  <%= link_to 'Back', root_path, class: 'btn btn-primary mt-2' %>
</p>